Add vagrant scripts
sdgtt/jenkins-shared-library pull request #46
Opened 2022-06-08 12:16 UTC by ccraluca

In this PR are two commits. 
The first will add some scripts for Jenkins Shared Libray in Vagrant project.
The second will add documentation for each scrippt.

Signed-off-by: Chis Raluca [raluca.chis@analog.com](mailto:raluca.chis@analog.com)

2022-06-08 18:03 UTC, tfcollins commented on vars/setup_jenkins_agent.groovy
> +    sh 'vagrant winrm --command "C:\\jenkins_win_vm_setup.ps1 http://10.48.65.12:8080/swarm/swarm-client.jar win-vm http://10.48.65.12:8080/ C:\\jenkins"'
1. Can this IP address be passed as an argument?
2. Can you change the name of the script from setup_jenkins_agent -> setup_jenkins_agent_on_vagrant_vm

2022-06-08 18:04 UTC, tfcollins commented on vars/setup_vagrant_box.groovy
> +    sh 'cp /mnt/storage1/jenkins-workspace/users/rchis/Vagrantfile .'
This path to the Vagrantfile should be configurable

2022-06-08 18:04 UTC, tfcollins commented on vars/setup_vagrant_box.groovy
> +    sh 'vagrant box add win test_no_updates.box --force'
Should the box name 'win' be an argument?

2022-06-08 18:05 UTC, tfcollins commented on vars/get_vagrant_vm_id.groovy
> +        if (lines[i].contains("rchis/SharedLibraries_Test")){
Is this the VM id "rchis/SharedLibraries_Test" ? Should this be an argument?

2022-06-10 11:15 UTC, ccraluca commented on vars/setup_vagrant_box.groovy
> +    sh 'vagrant box add win test_no_updates.box --force'
Yes, the box name and Vagrantfile path and other specific data will be passed as parameters

2022-06-10 11:26 UTC, ccraluca commented on vars/get_vagrant_vm_id.groovy
> +        if (lines[i].contains("rchis/SharedLibraries_Test")){
No, here the function checks for a VM inside rchis/SharedLibraries_Test workspace, so in this way will be sure that we will not use a VM that is running for other Jeknins job

2022-06-13 14:54 UTC, tfcollins commented
Is there a main function that wraps most of this logic for end users? For examples something like this:

```groovy
node {
    step('Run VM test') {
        vagrant('win') {
            bat 'hostname'
            ....
        }
    }
}
```

where the `vagrant` function above handles the state for you?

2022-06-16 08:22 UTC, ccraluca commented on vars/setup_jenkins_agent.groovy
> +    sh 'vagrant winrm --command "C:\\jenkins_win_vm_setup.ps1 http://10.48.65.12:8080/swarm/swarm-client.jar win-vm http://10.48.65.12:8080/ C:\\jenkins"'
IP passed as an argument and name of the script changed.

2022-06-17 12:41 UTC, ccraluca commented
V3: in this set of changes the documentation was updated according to previous changes and an example Vagrantfile was added for `run_closure()` function

2022-07-05 12:42 UTC, ccraluca commented
V4: example for end user added

2022-07-06 13:59 UTC, tfcollins requested changes

2023-06-14 16:31 UTC, tfcollins approved these changes

2023-06-14 16:31 UTC, merged